width: 1280             #图像宽度
height: 1024            #图像高度
Offset_x: 0             #X方向偏置
Offset_y: 0             #Y方向偏置

PixelFormat: 0         #像素格式，0: BayerRB8

FrameRateEnable: true   #使能 
FrameRate: 20           #帧率

ExposureTime: 1000      #曝光时间`
ExposureAuto: 2
AutoExposureTimeLowerLimit: 100
AutoExposureTimeUpperLimit: 10000

BalanceWhiteAuto: 0

Brightness: 60

GammaEnable: true
Gamma: 0.7         #伽马因子

GainAuto: 0             #亮度的固定增益

CalibrateEnable: false

ResizeEnable: false
DestinationHeight: 640
DestinationWidth: 640

# ImageCompressionMode: 1
# ImageCompressionQuality: 50

TriggerMode: 0

# hikrobot_camera:
#   rgb:
#     compressed:
#       format: "png"
#       png_level: 100
